### ISSUE TITLE
How to change colors in code?

### ISSUE THREAD

**Issue by thrilller** [BilalReffas/SwiftyGradient#2]
Any documentation about how to change the gradient on user action in code?

**Comment by BilalReffas** [comment]
You mean you want to set the color in code ?

**Comment by thrilller** [comment]
Yes, change the view gradient start & end colors  based on user info e.g gender. Apology i am new to iOS programming

**Comment by BilalReffas** [comment]
No problem we are a community :)
`let myView = SwiftyGradient(frame: CGRect(x: 100, y: 100, width: 100, height: 100))`
 `myView.startColor = UIColor(red:0.15, green:0.67, blue:0.42, alpha:1)`
 `myView.endColor = UIColor(red:0.82, green:0.31, blue:0.15, alpha:1)`
 `self.view.addSubview(myView)`

Like this you can do it with custom source code:)
